language: php

install:
- sudo apt-get install git-ftp

script:
- git config git-ftp.url "$FTP_SERVER/public_html"
- git config git-ftp.user "$FTP_USER"
- git config git-ftp.password "$FTP_PASS"
- git ftp init
