language: php

install:
- sudo apt-get install git-ftp

script:
- git config git-ftp.url "$FTP_SERVER"
- git config git-ftp.user "$FTP_USER"
- git config git-ftp.password "$FTP_PASS"
- git add *
- git status
- git commit -m 'Add Files'
- git ftp push
